import type { Product, User, Order } from './definitions';

export const products: Product[] = [
  {
    id: '1',
    name: 'Smart Watch',
    slug: 'smart-watch',
    description: 'A sleek and modern smart watch with a vibrant display, fitness tracking, and notification alerts. Stay connected on the go.',
    price: 299.99,
    category: 'Electronics',
    rating: 4.5,
    stock: 15,
    image: 'product-smart-watch',
  },
  {
    id: '2',
    name: 'Leather Backpack',
    slug: 'leather-backpack',
    description: 'A stylish and durable leather backpack with multiple compartments. Perfect for work, travel, or everyday use.',
    price: 149.50,
    category: 'Fashion',
    rating: 4.8,
    stock: 25,
    image: 'product-leather-backpack',
  },
  {
    id: '3',
    name: 'Wireless Headphones',
    slug: 'wireless-headphones',
    description: 'High-fidelity wireless headphones with noise-cancellation technology. Immerse yourself in pure, uninterrupted audio.',
    price: 199.00,
    category: 'Electronics',
    rating: 4.7,
    stock: 30,
    image: 'product-wireless-headphones',
  },
  {
    id: '4',
    name: 'Denim Jacket',
    slug: 'denim-jacket',
    description: 'A classic blue denim jacket that never goes out of style. A versatile wardrobe staple for any season.',
    price: 89.99,
    category: 'Fashion',
    rating: 4.6,
    stock: 40,
    image: 'product-denim-jacket',
  },
  {
    id: '5',
    name: 'Running Shoes',
    slug: 'running-shoes',
    description: 'Lightweight and comfortable running shoes designed for optimal performance and support. Reach your fitness goals in style.',
    price: 120.00,
    category: 'Sports',
    rating: 4.9,
    stock: 50,
    image: 'product-running-shoes',
  },
  {
    id: '6',
    name: 'Coffee Maker',
    slug: 'coffee-maker',
    description: 'An automatic drip coffee maker that brews the perfect cup every time. Start your day with rich, aromatic coffee.',
    price: 75.00,
    category: 'Home Goods',
    rating: 4.4,
    stock: 20,
    image: 'product-coffee-maker',
  },
  {
    id: '7',
    name: 'Aviator Sunglasses',
    slug: 'aviator-sunglasses',
    description: 'Stylish aviator sunglasses with UV protection. A timeless accessory for a cool, sophisticated look.',
    price: 65.00,
    category: 'Fashion',
    rating: 4.7,
    stock: 60,
    image: 'product-sunglasses',
  },
  {
    id: '8',
    name: 'Eco-Friendly Yoga Mat',
    slug: 'eco-friendly-yoga-mat',
    description: 'A non-slip, eco-friendly yoga mat made from sustainable materials. Find your balance and peace of mind.',
    price: 45.00,
    category: 'Sports',
    rating: 4.8,
    stock: 35,
    image: 'product-yoga-mat',
  },
];

export const users: User[] = [
  {
    id: '1',
    name: 'Admin User',
    email: 'admin@goshop.com',
    password: 'adminpassword',
    role: 'admin',
    avatar: 'user-avatar-1',
  },
  {
    id: '2',
    name: 'Regular User',
    email: 'user@goshop.com',
    password: 'userpassword',
    role: 'user',
    avatar: 'user-avatar-2',
  },
];

export const orders: Order[] = [
  {
    id: 'ORD001',
    userId: '2',
    userName: 'Regular User',
    items: [
      { id: '1', name: 'Smart Watch', price: 299.99, image: 'product-smart-watch', quantity: 1 },
      { id: '4', name: 'Denim Jacket', price: 89.99, image: 'product-denim-jacket', quantity: 1 },
    ],
    total: 389.98,
    status: 'Delivered',
    shippingAddress: {
      address: '123 Main St',
      city: 'Anytown',
      state: 'CA',
      zip: '12345',
    },
    createdAt: '2023-10-26T10:00:00Z',
  },
  {
    id: 'ORD002',
    userId: '2',
    userName: 'Regular User',
    items: [
      { id: '5', name: 'Running Shoes', price: 120.00, image: 'product-running-shoes', quantity: 2 },
    ],
    total: 240.00,
    status: 'Shipped',
    shippingAddress: {
      address: '123 Main St',
      city: 'Anytown',
      state: 'CA',
      zip: '12345',
    },
    createdAt: '2023-10-28T14:30:00Z',
  },
];
